### ISSUE TITLE
Stackexchange feature Not working!

### ISSUE THREAD

**Issue by janaSunrise** [The-Codin-Hole/HotWired-Bot#9]
Error traceback : 
```py
Traceback (most recent call last):
  File "C:\Users\Admin\.virtualenvs\HotWired-Bot-z3aU_myq\lib\site-packages\discord\ext\commands\bot.py", line 596, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Admin\Desktop\HotWired-Bot\cogs\coding.py", line 12, in <module>
    import stackexchange as se
  File "C:\Users\Admin\.virtualenvs\HotWired-Bot-z3aU_myq\lib\site-packages\stackexchange\__init__.py", line 18, in <module>
    from .rest import *
  File "C:\Users\Admin\.virtualenvs\HotWired-Bot-z3aU_myq\lib\site-packages\stackexchange\rest\__init__.py", line 3, in <module>
    from answer import *
ModuleNotFoundError: No module named 'answer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 100, in <module>
    SetupBot(client)
  File "main.py", line 82, in SetupBot
    bot.load_extension("cogs.coding")
  File "C:\Users\Admin\.virtualenvs\HotWired-Bot-z3aU_myq\lib\site-packages\discord\ext\commands\bot.py", line 653, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\Admin\.virtualenvs\HotWired-Bot-z3aU_myq\lib\site-packages\discord\ext\commands\bot.py", line 599, in _load_from_module_spec        
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.coding' raised an error: ModuleNotFoundError: No module named 'answer'
```

**Comment by Theodore-Robinson** [comment]
This issue is for developers in our team, not for github. We'll be discussing about this on discord, not here.
